// src/renderer/App.tsx
/**
 * Chips AppTemplate - 根组件（React）
 * @module App
 */

import {
  Button,
  ConfigProvider,
  Tabs,
  ThemeProvider,
  type TabItem,
} from '@chips/components';
import { useCallback, useEffect, useRef, useState } from 'react';
import AppHeader from './components/AppHeader';
import StatusBar from './components/StatusBar';
import CoreTestPanel from './components/panels/CoreTestPanel';
import EventTestPanel from './components/panels/EventTestPanel';
import I18nTestPanel from './components/panels/I18nTestPanel';
import SdkTestPanel from './components/panels/SdkTestPanel';
import ThemeTestPanel from './components/panels/ThemeTestPanel';
import ComponentShowcasePanel from './components/panels/ComponentShowcasePanel';
import { t, initializeI18n, setLocale } from './services/i18n-service';
import {
  destroyKeyboard,
  initializeKeyboard,
  registerStandardShortcuts,
} from './services/keyboard-service';
import { appLogger } from './services/logger-service';
import { getSdkSync } from './services/sdk-service';
import { getTheme, initializeTheme, setTheme } from './services/theme-service';
import { useAppStore } from './state/app-store';
import type { Locale, ThemeType } from './types';
import { themeDefaults, themeTokens } from './theme/theme-tokens';

export default function App() {
  const appStore = useAppStore();
  const {
    locale,
    theme,
    isReady,
    errorMessage,
    setState: setAppState,
    setLocale: setAppLocale,
    setTheme: setAppTheme,
    setConnectionState,
    setSdkReady,
    setError,
  } = appStore;
  const [activePanel, setActivePanel] = useState('sdk');

  const initialLocaleRef = useRef(locale);
  const localeRef = useRef(locale);
  const themeRef = useRef(theme);

  useEffect(() => {
    localeRef.current = locale;
  }, [locale]);

  useEffect(() => {
    themeRef.current = theme;
  }, [theme]);

  const applyLocale = useCallback(
    (locale: Locale) => {
      setLocale(locale);
      setAppLocale(locale);
    },
    [setAppLocale],
  );

  const applyTheme = useCallback(
    (theme: ThemeType) => {
      setTheme(theme);
      setAppTheme(theme);
    },
    [setAppTheme],
  );

  useEffect(() => {
    let disposed = false;
    let removeMenuListener: (() => void) | undefined;

    const init = async () => {
      try {
        setAppState('loading');
        setConnectionState('connecting');

        appLogger.info('initializing application');

        await initializeI18n(initialLocaleRef.current);

        const sdk = getSdkSync();
        setSdkReady(Boolean(sdk?.isReady));
        setConnectionState(sdk?.isConnected ? 'connected' : 'disconnected');

        initializeTheme();
        const detectedTheme = getTheme();
        setAppTheme(detectedTheme);

        initializeKeyboard();
        registerStandardShortcuts({
          onToggleTheme: () => {
            const next = themeRef.current === 'default-dark' ? 'default-light' : 'default-dark';
            applyTheme(next);
          },
          onToggleLocale: () => {
            const next = localeRef.current === 'zh-CN' ? 'en-US' : 'zh-CN';
            applyLocale(next);
          },
        });

        if (window.electronAPI?.onMenuAction) {
          removeMenuListener = window.electronAPI.onMenuAction((action: string) => {
            appLogger.info('menu action received', { action });
          });
        }

        if (disposed) {
          return;
        }

        setAppState('ready');
        appLogger.info('application initialized successfully');
      } catch (error) {
        const message = error instanceof Error ? error.message : t('app.error_unknown');
        setConnectionState('error');
        setError(message);
        appLogger.error('initialization failed', { error: String(error) });
      }
    };

    void init();

    return () => {
      disposed = true;
      removeMenuListener?.();
      destroyKeyboard();
    };
  }, [
    applyLocale,
    applyTheme,
    setAppState,
    setConnectionState,
    setSdkReady,
    setAppTheme,
    setError,
  ]);

  const panelItems: TabItem[] = [
    { id: 'sdk', label: t('test.sdk.title'), content: <SdkTestPanel /> },
    { id: 'i18n', label: t('test.i18n.title'), content: <I18nTestPanel /> },
    { id: 'theme', label: t('test.theme.title'), content: <ThemeTestPanel /> },
    {
      id: 'components',
      label: t('test.components.title'),
      content: <ComponentShowcasePanel />,
    },
    { id: 'event', label: t('test.event.title'), content: <EventTestPanel /> },
    { id: 'core', label: t('test.core.title'), content: <CoreTestPanel /> },
  ];

  const retryInit = () => {
    setAppState('loading');
    setError(null);
    globalThis.location.reload();
  };

  return (
    <ThemeProvider className="app-theme-root" tokens={themeTokens[theme]} defaults={themeDefaults}>
      <ConfigProvider
        config={{
          appLocale: locale,
          appTheme: theme,
        }}
      >
        <div className="app-container">
          {!isReady && !errorMessage ? (
            <div className="app-loading">
              <div className="loading-spinner" />
              <p className="loading-text">{t('app.loading')}</p>
            </div>
          ) : null}

          {errorMessage ? (
            <div className="app-error">
              <p className="error-title">{t('app.error_title')}</p>
              <p className="error-message">{errorMessage}</p>
              <Button className="error-retry-btn" onClick={retryInit}>
                {t('app.error_retry')}
              </Button>
            </div>
          ) : null}

          {isReady ? (
            <>
              <AppHeader
                locale={locale}
                theme={theme}
                onLocaleChange={applyLocale}
                onThemeToggle={(darkMode) =>
                  applyTheme(darkMode ? 'default-dark' : 'default-light')
                }
              />

              <main className="app-main">
                <Tabs
                  chipsScope="app-tabs"
                  className="test-tabs"
                  value={activePanel}
                  onValueChange={(value) => setActivePanel(value)}
                  items={panelItems}
                />
              </main>

              <StatusBar />
            </>
          ) : null}
        </div>
      </ConfigProvider>
    </ThemeProvider>
  );
}

// src/renderer/App.vue
<script setup lang="ts">
/**
 * Chips AppTemplate - 根组件
 * @module App
 * @description 薯片生态标准模板应用入口
 *
 * 遵循规范：
 * - 多语言（生态共用 11）：所有文本通过 t() 获取
 * - 主题系统（设计原稿 12）：使用 CSS 变量，零硬编码样式
 * - 组件库集成：使用 ChipsProvider + ThemeProvider 包裹
 */

import { ref, onMounted, onUnmounted, computed } from 'vue';
import { ChipsProvider, ThemeProvider } from '@chips/components';
import { useAppStore } from './stores/app-store';
import { initializeI18n, t } from './services/i18n-service';
import { initializeTheme } from './services/theme-service';
import {
  initializeKeyboard,
  destroyKeyboard,
  registerStandardShortcuts,
} from './services/keyboard-service';
import { appLogger } from './services/logger-service';
import AppHeader from './components/app-header/AppHeader.vue';
import StatusBar from './components/status-bar/StatusBar.vue';
import SdkTestPanel from './components/test-panels/SdkTestPanel.vue';
import I18nTestPanel from './components/test-panels/I18nTestPanel.vue';
import ThemeTestPanel from './components/test-panels/ThemeTestPanel.vue';
import EventTestPanel from './components/test-panels/EventTestPanel.vue';
import CoreTestPanel from './components/test-panels/CoreTestPanel.vue';

const appStore = useAppStore();

/** 应用是否就绪 */
const isReady = computed(() => appStore.isReady);
const errorMessage = computed(() => appStore.errorMessage);
const locale = computed(() => appStore.locale);
const theme = computed(() => appStore.theme);

/** 活动测试面板 */
const activePanel = ref<string>('sdk');

/**
 * 切换活动测试面板
 */
function setActivePanel(panel: string): void {
  activePanel.value = panel;
}

/**
 * 初始化应用
 */
onMounted(async () => {
  try {
    appLogger.info('initializing application');

    // 1. 初始化 i18n
    await initializeI18n(appStore.locale);
    appStore.setSdkReady(true);

    // 2. 初始化主题
    initializeTheme();

    // 3. 初始化快捷键
    initializeKeyboard();
    registerStandardShortcuts({
      onToggleTheme: () => {
        import('./composables/use-theme').then(({ useTheme: useThemeFn }) => {
          const { toggleTheme: toggle } = useThemeFn();
          toggle();
        });
      },
    });

    // 4. 监听菜单事件
    if (window.electronAPI?.onMenuAction) {
      window.electronAPI.onMenuAction((action: string) => {
        appLogger.info('menu action received', { action });
      });
    }

    // 5. 设置就绪
    appStore.setState('ready');
    appLogger.info('application initialized successfully');
  } catch (error) {
    const message = error instanceof Error ? error.message : t('app.error_unknown');
    appStore.setError(message);
    appLogger.error('initialization failed', { error: String(error) });
  }
});

onUnmounted(() => {
  destroyKeyboard();
});

/**
 * 重试初始化
 */
function handleRetry(): void {
  appStore.setState('loading');
  appStore.setError(null);
  globalThis.location.reload();
}
</script>

<template>
  <ThemeProvider :theme="theme">
    <ChipsProvider :locale="locale" :theme="theme">
      <div class="app-container">
        <!-- 加载状态 -->
        <div v-if="!isReady && !errorMessage" class="app-loading">
          <div class="loading-spinner"></div>
          <p class="loading-text">{{ t('app.loading') }}</p>
        </div>

        <!-- 错误状态 -->
        <div v-else-if="errorMessage" class="app-error">
          <p class="error-title">{{ t('app.error_title') }}</p>
          <p class="error-message">{{ errorMessage }}</p>
          <button class="error-retry-btn" @click="handleRetry">
            {{ t('app.error_retry') }}
          </button>
        </div>

        <!-- 应用主体 -->
        <template v-else>
          <AppHeader />

          <main class="app-main">
            <!-- 测试面板导航 -->
            <nav class="test-nav">
              <h2 class="test-nav-title">{{ t('test.title') }}</h2>
              <div class="test-nav-tabs">
                <button
                  v-for="panel in ['sdk', 'i18n', 'theme', 'event', 'core']"
                  :key="panel"
                  class="test-nav-tab"
                  :class="{ active: activePanel === panel }"
                  @click="setActivePanel(panel)"
                >
                  {{ t(`test.${panel}.title`) }}
                </button>
              </div>
            </nav>

            <!-- 测试面板内容 -->
            <div class="test-content">
              <SdkTestPanel v-if="activePanel === 'sdk'" />
              <I18nTestPanel v-else-if="activePanel === 'i18n'" />
              <ThemeTestPanel v-else-if="activePanel === 'theme'" />
              <EventTestPanel v-else-if="activePanel === 'event'" />
              <CoreTestPanel v-else-if="activePanel === 'core'" />
            </div>
          </main>

          <StatusBar />
        </template>
      </div>
    </ChipsProvider>
  </ThemeProvider>
</template>

<style>
/* 全局重置 - 使用 CSS 变量（主题系统规范） */
*,
*::before,
*::after {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html,
body {
  height: 100%;
  font-family: var(--chips-font-family, system-ui, -apple-system, sans-serif);
  font-size: var(--chips-font-size-base, 1rem);
  color: var(--chips-color-text, #1e293b);
  background-color: var(--chips-color-background, #ffffff);
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#app {
  height: 100%;
}
</style>

<style scoped>
.app-container {
  display: flex;
  flex-direction: column;
  height: 100vh;
  background-color: var(--chips-color-background);
  color: var(--chips-color-text);
}

/* 加载状态 */
.app-loading {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: var(--chips-spacing-md);
}

.loading-spinner {
  width: 36px;
  height: 36px;
  border: 3px solid var(--chips-color-border);
  border-top-color: var(--chips-color-primary);
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}

.loading-text {
  color: var(--chips-color-text-secondary);
  font-size: var(--chips-font-size-sm);
}

/* 错误状态 */
.app-error {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: var(--chips-spacing-sm);
  padding: var(--chips-spacing-xl);
}

.error-title {
  color: var(--chips-color-error);
  font-size: var(--chips-font-size-lg);
  font-weight: var(--chips-font-weight-semibold);
}

.error-message {
  color: var(--chips-color-text-secondary);
  text-align: center;
  max-width: 400px;
}

.error-retry-btn {
  margin-top: var(--chips-spacing-md);
  padding: var(--chips-spacing-sm) var(--chips-spacing-lg);
  background-color: var(--chips-color-primary);
  color: #ffffff;
  border: none;
  border-radius: var(--chips-radius-md);
  font-weight: var(--chips-font-weight-medium);
  cursor: pointer;
  transition: opacity var(--chips-duration-fast) var(--chips-easing-default);
}

.error-retry-btn:hover {
  opacity: 0.9;
}

/* 主体 */
.app-main {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  padding: var(--chips-spacing-lg);
  gap: var(--chips-spacing-md);
}

/* 测试导航 */
.test-nav {
  display: flex;
  flex-direction: column;
  gap: var(--chips-spacing-sm);
}

.test-nav-title {
  font-size: var(--chips-font-size-lg);
  font-weight: var(--chips-font-weight-semibold);
  color: var(--chips-color-text);
}

.test-nav-tabs {
  display: flex;
  gap: var(--chips-spacing-xs);
  border-bottom: 1px solid var(--chips-color-border);
  padding-bottom: var(--chips-spacing-sm);
}

.test-nav-tab {
  padding: var(--chips-spacing-xs) var(--chips-spacing-md);
  background: transparent;
  border: 1px solid transparent;
  border-radius: var(--chips-radius-sm);
  color: var(--chips-color-text-secondary);
  font-size: var(--chips-font-size-sm);
  cursor: pointer;
  transition: all var(--chips-duration-fast) var(--chips-easing-default);
}

.test-nav-tab:hover {
  color: var(--chips-color-text);
  background-color: var(--chips-color-surface);
}

.test-nav-tab.active {
  color: var(--chips-color-primary);
  border-color: var(--chips-color-primary);
  background-color: var(--chips-color-surface);
}

/* 测试内容 */
.test-content {
  flex: 1;
  overflow-y: auto;
}
</style>
